artifacts_root: "artifacts"

image:
  local_full_path: "/Volumes/EXTDISK/Cisco-IOS/cat8k_iosxe.17.09.04a.SPA.bin"
  filename: "cat8k_iosxe.17.09.04a.SPA.bin"
  expected_md5: "0123456789abcdef0123456789abcdef"
  remote_path: "bootflash:/cat8k_iosxe.17.09.04a.SPA.bin"

device_fs:
  remote_fs: "bootflash:"
  remote_dir: "bootflash:/"   
  space_factor: 1.5

behavior:
  max_workers: 5
  connect_timeout: 20
  cmd_timeout: 60
  scp_enable_before_upload: true
  scp_disable_after_upload: true
  reload_timeout: 900
  probe_interval: 10

cli:
  backend: "netmiko"        # netmiko | scrapli

transfer:
  method: "scp"             # scp | copy_command
  
#for copy_command method, the server is my local machine running a simple HTTP server to serve the image file; 
#the devices will pull the image from this server using "copy http://
  copy:
    server_ip: "192.168.2.31"
    server_port: 8000
    protocol: "http"
  